install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-1.17.0-x86_64-pc-windows-gnu.exe'
  - rust-1.17.0-x86_64-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build_script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features

test_script:
  - cargo test --verbose
  - cargo test --verbose --no-default-features
