(function() {var implementors = {};
implementors["bstr"] = [{"text":"impl Default for BString","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Default for &amp;'a BStr","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Default for &amp;'a mut BStr","synthetic":false,"types":[]}];
implementors["byteorder"] = [{"text":"impl Default for BigEndian","synthetic":false,"types":[]},{"text":"impl Default for LittleEndian","synthetic":false,"types":[]}];
implementors["csv"] = [{"text":"impl Default for ByteRecord","synthetic":false,"types":[]},{"text":"impl Default for ReaderBuilder","synthetic":false,"types":[]},{"text":"impl Default for StringRecord","synthetic":false,"types":[]},{"text":"impl Default for WriterBuilder","synthetic":false,"types":[]},{"text":"impl Default for QuoteStyle","synthetic":false,"types":[]},{"text":"impl Default for Terminator","synthetic":false,"types":[]},{"text":"impl Default for Trim","synthetic":false,"types":[]}];
implementors["csv_core"] = [{"text":"impl Default for Reader","synthetic":false,"types":[]},{"text":"impl Default for ReaderBuilder","synthetic":false,"types":[]},{"text":"impl Default for WriterBuilder","synthetic":false,"types":[]},{"text":"impl Default for Writer","synthetic":false,"types":[]},{"text":"impl Default for Terminator","synthetic":false,"types":[]},{"text":"impl Default for QuoteStyle","synthetic":false,"types":[]}];
implementors["encode_unicode"] = [{"text":"impl Default for Utf8Char","synthetic":false,"types":[]},{"text":"impl Default for Utf16Char","synthetic":false,"types":[]},{"text":"impl&lt;B:&nbsp;Default + Borrow&lt;u8&gt;, I:&nbsp;Default + Iterator&lt;Item = B&gt;&gt; Default for Utf8CharMerger&lt;B, I&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Default for Utf8CharDecoder&lt;'a&gt;","synthetic":false,"types":[]},{"text":"impl&lt;B:&nbsp;Default + Borrow&lt;u16&gt;, I:&nbsp;Default + Iterator&lt;Item = B&gt;&gt; Default for Utf16CharMerger&lt;B, I&gt;","synthetic":false,"types":[]},{"text":"impl&lt;'a&gt; Default for Utf16CharDecoder&lt;'a&gt;","synthetic":false,"types":[]}];
implementors["itoa"] = [{"text":"impl Default for Buffer","synthetic":false,"types":[]}];
implementors["prettytable"] = [{"text":"impl Default for Cell","synthetic":false,"types":[]},{"text":"impl Default for Row","synthetic":false,"types":[]},{"text":"impl Default for LineSeparator","synthetic":false,"types":[]},{"text":"impl Default for TableFormat","synthetic":false,"types":[]}];
implementors["ryu"] = [{"text":"impl Default for Buffer","synthetic":false,"types":[]}];
implementors["serde"] = [{"text":"impl Default for IgnoredAny","synthetic":false,"types":[]}];
implementors["term"] = [{"text":"impl Default for Param","synthetic":false,"types":[]},{"text":"impl Default for Variables","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()